Fix `rr-overlay.nix` for modern nixpkgs
Fixes the error:
```
error: anonymous function at /nix/store/lh73pszzv2569h92dn8n56cccdxyvn9g-nixos-21.11pre301985.23cd13167a1/nixos/pkgs/development/tools/analysis/rr/default.nix:1:1 called with unexpected argument 'stdenv', at /nix/store/lh73pszzv2569h92dn8n56cccdxyvn9g-nixos-21.11pre301985.23cd13167a1/nixos/lib/customisation.nix:69:16
```
`rr` in nixpkgs now expects a `gcc9Stdenv` argument instead of a `stdenv` argument.