Update wrapFirefox call to remove name argument
The "name" argument has been removed in the master version of nixpkgs:

 https://github.com/NixOS/nixpkgs/commit/d34d84a61da7cf332e470b65ab05f2d995026090

This causes the overlay to fail with the following error:

```
error: 'wrapper' at /nix/store/2h5z1dm03waymz8b383szl5bc8a21f74-nixos-20.03pre203172.0ee0489d42e/nixos/pkgs/applications/networking/browsers/firefox/wrapper.nix:21:5 called with unexpected argument 'name', at /nix/store/2h5z1dm03waymz8b383szl5bc8a21f74-nixos-20.03pre203172.0ee0489d42e/nixos/lib/customisation.nix:69:16
```