Fix evaluation error as of NixOS/nixpkgs#377863
    error: function 'wrapper' called with unexpected argument 'desktopName'
    at …/nixpkgs/pkgs/applications/networking/browsers/firefox/wrapper.nix:27:5:
        26|   wrapper =
        27|     { applicationName ? browser.binaryName or (lib.getName browser) # Note: this is actually *binary* name and is different from browser.passthru.applicationName, which is *app* name!
          |     ^
        28|     , pname ? applicationName

See
https://github.com/NixOS/nixpkgs/commit/b856437376fd346ed9054a671ec602eff16f496f.

Signed-off-by: Anders Kaseorg <andersk@mit.edu>